### ISSUE TITLE
working with lightbox2

### ISSUE THREAD

**Issue by ErollJr** [Skyleen77/next-nprogress-bar#14]
In the context of using lightbox2, the modal image opens when the 'href' is triggered. However, upon clicking, an issue arises where the loading indicator persists indefinitely without completing the process.

**Comment by Skyleen77** [comment]
I understand the problem, but I don't know how I could adapt the progress bar without changing how it works. Feel free to make a pull request.

**Comment by Skyleen77** [comment]
You can now disable the progress bar on a link using the `data-disable-nprogress={true}` attribute
