### ISSUE TITLE
Adding progressbar ends with all pages  deopted into client-side rendering

### ISSUE THREAD

**Issue by eduardochiaro** [Skyleen77/next-nprogress-bar#17]
After adding progressbar into `layout.tsx` as described in the documentation, i notice that all pages were marked as `deopted into client-side rendering`. 

I find a solution by wrapping the component into a Suspense boundary, as described here [https://nextjs.org/docs/messages/deopted-into-client-rendering](url)  

The provider function looks like this
```
function Fallback() {
  return <></>;
}

export default function Providers({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Suspense fallback={<Fallback />}>
        <ProgressBar height="5px" color="#fffd00" options={{ showSpinner: false }} shallowRouting  />
      </Suspense>
      {children}
    </>
  );
}
```

**Comment by kurisu994** [comment]
same problem

**Comment by darrylmorley** [comment]
Same

**Comment by Skyleen77** [comment]
My bad for this error, you are right.

This will be fixed in the next update.
