### ISSUE TITLE
Spinner doesn't work in the app directory version

### ISSUE THREAD

**Issue by mamadfar** [Skyleen77/next-nprogress-bar#2]
I'm using Next 13.4.6.
The spinner doesn't work in the app directory version but the progress bar works fine.

**Comment by Skyleen77** [comment]
You're right, I just rolled out a plugin update that changes that.

You can now properly use nprogress options like this:
```jsx
<ProgressBar
  color={primaryColor}
  height="3px"
  options={{ showSpinner: true }}
  appDirectory
  shallowRouting
/>
```

If you encounter any other problems, don't hesitate to ask me.

**Comment by mamadfar** [comment]
> 

WOW!

Thank you for your quick reply and quick fix!
The spinner is working perfectly now. 🌹
