### ISSUE TITLE
An option to pass a custom arePropsEqual argument?

### ISSUE THREAD

**Issue by richardcalahan** [Skyleen77/next-nprogress-bar#20]
The component is memoized but the second `arePropsEqual` argument is hard coded as `() => true`. This means we can't dynamically change any of the props, e.g., color, from page to page. 

Possible to remove the hard coding or allow for a custom option?

**Comment by Skyleen77** [comment]
This will be fixed in the next update.

You can use the props `shouldCompareComplexProps={true}`.
