### ISSUE TITLE
Show progress on query param change with useRouter

### ISSUE THREAD

**Issue by Abdubek** [Skyleen77/next-nprogress-bar#21]
<img width="559" alt="image" src="https://github.com/Skyleen77/next-nprogress-bar/assets/16240224/96494667-cc93-4511-a5a1-7212eb150368">

I'm trying to show a progress bar when changing query params using useRouter, but it's not happening. isSameURL function does not check query params

**Comment by nodegin** [comment]
Getting the same issue, the only workaround at the moment is seem to be manually importing NProgress.
