### ISSUE TITLE
Not working in loading.js routes

### ISSUE THREAD

**Issue by patrykmaron** [Skyleen77/next-nprogress-bar#28]
Next has an option to load loading UI first before the actual route by creating loading.tsx file in the same folder as the page.tsx.

More info on this here: https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

What would be cool, if this package supported this pattern, and display the loading bar whilst in loading.tsx state, which as of current doesn't

**Comment by Skyleen77** [comment]
It's a very good idea.

This is not planned at the moment but if you want to do a PR, I would study it carefully.
