### ISSUE TITLE
router.replace() not triggering progress bar

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [Skyleen77/next-nprogress-bar#29]
Hi thanks for this library, I think this library not implementing progress bar yet for the `replace` method? but `push` & `back` already implemented here. am i correct?

<img width="833" alt="image" src="https://github.com/Skyleen77/next-nprogress-bar/assets/63343105/6d9b5d8e-d753-4ee3-be5a-930dc48bcbda">

**Comment by pingustar** [comment]
yepp, came here to say the same

**Comment by ImamAlfariziSyahputra** [comment]
@Skyleen77

**Comment by boreyko1** [comment]
meanwhile you can easily wrap it yourself with something like:
```ts
  const router = useNextRouter()

  const replace = React.useCallback(
    (
      href: string,
      options?: NavigateOptions | undefined,
      NProgressOptions?: NProgressOptions,
    ) => {
      if (NProgressOptions?.showProgressBar === false) {
        return router.back()
      }

      NProgress.start()

      return router.replace(href, options)
    },
    [router],
  )
```

**Comment by Skyleen77** [comment]
This will be added in the next version which is coming soon.

**Comment by ImamAlfariziSyahputra** [comment]
> This will be added in the next version which is coming soon.

glad to hear that! I think you could close the issue after the feature is added
