### ISSUE TITLE
NProgressOptions doesn't have any type suggestion with TypeScript

### ISSUE THREAD

**Issue by mamadfar** [Skyleen77/next-nprogress-bar#3]
I'm using Next 13.4.6.
It will be great if you integrate the NProgressOptions in this awesome package.

**Comment by Skyleen77** [comment]
Hello, I will work on this.

I'll keep you informed.

**Comment by Skyleen77** [comment]
I just updated the plugin to version 1.2.5.

You can now import the NProgressOptions type directly from the plugin like this:
```js
import type { NProgressOptions } from 'next-nprogress-bar';
```

**Comment by mamadfar** [comment]
> I just updated the plugin to version 1.2.5.
> 
> You can now import the NProgressOptions type directly from the plugin like this:
> 
> ```js
> import type { NProgressOptions } from 'next-nprogress-bar';
> ```

Great work!
Thank you for your quick fix.
Now it's working perfectly.
