### ISSUE TITLE
Vercel build error

### ISSUE THREAD

**Issue by eltac-malik** [Skyleen77/next-nprogress-bar#36]
How can l fix that? 
 
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error

 ✓ Generating static pages (4/4) 

> Export encountered errors on following paths:
        /_not-found
        /page: /
error Command failed with exit code 1.

**Comment by Skyleen77** [comment]
You are absolutely right!

This will be fixed in the next version.
