### ISSUE TITLE
Progress bar triggers with blob links

### ISSUE THREAD

**Issue by billypap1** [Skyleen77/next-nprogress-bar#38]
I use next-progress-bar and it works great for all links (<Link ..) but I have an issue with PDFKit.

I create a pdf file and I use the PDFDownloadLink component to download it. It creates a link in this format: 
`blob:http://localhost:3000/62221acd-6555-4e01-907a-01af172e33b7`

When I click this link to download the file, it triggers the progress-bar and starts to load.

Any idea to disable it in blob links?

**Comment by Skyleen77** [comment]
Hey, thanks for your feedback.

I just fixed this in version 2.3.2.

You don't need to do anything special, just upgrade to version 2.3.2 and it should be fixed.

**Comment by Skyleen77** [comment]
No problem, don't hesitate if you encounter other problems
