### ISSUE TITLE
ProgressBar not working when using router.push to redirect

### ISSUE THREAD

**Issue by rice2411** [Skyleen77/next-nprogress-bar#4]
Hi, when i'm using link from next/link its fine but, when i try to handle event click and then using router.push its still redirect but the progressbar not showing anymore, is that a bug or i miss some thing

**Comment by Skyleen77** [comment]
Thank you rizkiandrianto for this idea. After searching for better ideas I couldn't find any. v2 is now available with a useRouter supporting NProgress.

Don't hesitate to look at the documentation for more information on this subject.

If you encounter any other problems, don't hesitate to ask me.
