### ISSUE TITLE
np pregesss not running based on route.event.on similar to page router

### ISSUE THREAD

**Issue by detailswes** [Skyleen77/next-nprogress-bar#45]
here is my code 

"use client";
import { AppProgressBar as ProgressBar } from "next-nprogress-bar";

export function RouteChangeListener() {

  return (
    <ProgressBar
      height="4px"
      color="#fffd00"
      options={{ showSpinner: false }}
      shallowRouting
    />
  );
}

here i am using it 

"use client";
import createCache from "@emotion/cache";
import { CacheProvider } from "@emotion/react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Gtm from "next-gtm";
import dynamic from "next/dynamic";
import { Suspense, useEffect } from "react";
import { Provider } from "react-redux";
import FullPageLoader from "ui/components/Loader/FullPageLoader";
import { AmplitudeInit, InitAnalyticsManager } from "ui/utils/amplitude";
import ErrorBoundary from "../_components/ErrorBoundary";
import SessionHandler from "../_components/session-handler";
import { default as Layout } from "../layouts";
import { store } from "../store";
import { RouteChangeListener } from "./route-change-listener";
const MaintenanceView = dynamic(() => import("ui/components/maintenance-mode"));

AmplitudeInit();

const theme = createTheme();

export function Providers({ children, nonce }) {
  const cache = createCache({
    key: "client-app",
    nonce: nonce,
    prepend: true,
  });

  const isMaintenanceMode = process.env.MAINTENANCE_MODE?.toString();
  const HardCodedMode = false;

  useEffect(() => {
    InitAnalyticsManager();
  }, []);

  if (isMaintenanceMode === "true" || HardCodedMode) {
    return <MaintenanceView />;
  }

  return (
    <Suspense fallback={<FullPageLoader loading={true} />}>
      <Provider store={store}>
        <RouteChangeListener />
        <Gtm id={process.env.GTM_ID} />
        <CacheProvider value={cache}>
          <AppRouterCacheProvider
            options={{
              // enableCssLayer: true,
              nonce: nonce,
              insertionPoint: true,
            }}
          >
            <GoogleOAuthProvider
              clientId={process.env.GOOGLE_ACCOUNT_CLIENT_ID}
              nonce={nonce}
            >
              <ErrorBoundary>
                <SessionHandler>
                  <ThemeProvider theme={theme}>
                    <Layout>{children}</Layout>
                  </ThemeProvider>
                </SessionHandler>
              </ErrorBoundary>
            </GoogleOAuthProvider>
          </AppRouterCacheProvider>
        </CacheProvider>
      </Provider>
    </Suspense>
  );
}

**Comment by Skyleen77** [comment]
With the app directory there is no longer `router.event` so nprogress is automatically added to the link elements as a click event
