### ISSUE TITLE
how to use `data-disable-nprogress={true}`

### ISSUE THREAD

**Issue by yikayiyo** [Skyleen77/next-nprogress-bar#47]
## what happened

When I am on the homepage ('/'), clicking on 'Blogs' redirects me to the '/blogs' page and the progress bar displays correctly. However, when I am on the homepage ('/'), clicking on 'Test' does not redirect me to the '/blogs' page, and the progress bar also does not display. Is this the correct way to use `data-disable-nprogress={true}`? The readme doc may need to update about this.

```jsx
'use client'

import Link from 'next/link'

const TopNav = () => {
  return ( 
    <nav className='bg-[#dfa] p-2 flex items-center gap-2'>
      <Link href={'/'}>Home</Link>
      <Link className='border border-1 border-blue-500 flex items-center' href={'/blogs'} data-disable-nprogress={true}>
        <div className='p-2'>
          Blogs
        </div>
        <span className='bg-red-200 p-2' onClick={e=>{
          e.preventDefault()
        }}>Test</span>
      </Link>
      <Link href={'/about'}>About</Link>
    </nav>
   );
}
 
export default TopNav;
```

**Comment by Skyleen77** [comment]
to disable progress bar when you have `e.preventDefault()` on child element please upgrade to the 2.3.10 and use `data-prevent-nprogress={true}` : 
```jsx
<span className='bg-red-200 p-2' onClick={e=>{
    e.preventDefault()
}} data-prevent-nprogress={true}>Test</span>
```
