### ISSUE TITLE
how to force the progress bar when navigating to the same url

### ISSUE THREAD

**Issue by noobCode-69** [Skyleen77/next-nprogress-bar#50]
hey @Skyleen77 thanks for this awesome package

I only have one feature requirement .

- I have a search button that navigates me to certain routes with  `router.push` 
- When I  navigate to the exact same routes I don't see any progress bar 
- This is because of early return in the `router.push` over here
 
![image](https://github.com/Skyleen77/next-nprogress-bar/assets/76926762/ebbcfd65-d62f-4d40-ba21-30d36296a44f)

- I know this is not a bug and intentional behaviour but I want to show that progress bar because it's a search button and we want to show the user that they're getting fresh data

something like this will be fine
```
if(// same url){
// start progress
// end progress
// rest of the logic
}
```

**Comment by Skyleen77** [comment]
upgrade to the 2.3.10 and use disableSameURL={false} on the ProgressBar.

**Comment by noobCode-69** [comment]
awesome thanks

**Comment by noobCode-69** [comment]
hmmm it's not working 
it seems you have only added it for anchor elements but not for `router.push`

**Comment by Skyleen77** [comment]
I'm sorry for that, I add a disableSameURL option on `router.push()` on the 2.3.11.

You can use it like this : 
```js
router.push('/url', undefined, { disableSameURL: false })
```

**Comment by noobCode-69** [comment]
many thanks

**Comment by Skyleen77** [comment]
It is normal that this does not stop because you are not changing pages, you can manually use the `stopProgress` function to stop it.
To mock you can also use the `startProgress` function to launch the progress bar.
```jsx
<button onClick={() => startProgress()}>Start progress</button>
<button onClick={() => stopProgress()}>Stop progress</button>
```

You can send me your code if you want so that we can find the best solution.
