### ISSUE TITLE
Progress Bar Animation Triggered in Next.js Link with Nested Button Despite preventDefault and stopPropagation

### ISSUE THREAD

**Issue by ciruz** [Skyleen77/next-nprogress-bar#52]
I've encountered an issue using Next.js where nesting a button inside a Link component and attempting to stop the event propagation and default behavior does not prevent the progress bar animation from being triggered. This occurs even when the URL does not change as a result of the button click.

I have set up an example to demonstrate this issue: [CodeSandbox Example](https://codesandbox.io/p/devbox/happy-violet-78hc3v)

![progressbar](https://github.com/Skyleen77/next-nprogress-bar/assets/987947/9bdc8dbd-d709-482b-9e5d-5a19170bbda4)

```javascript
// Next.js Link wrapping a custom component with a button
<Link href="/test">
  <Box />
</Link>

// Box component with a button that should prevent link navigation
"use client";

export default function Box() {
  return (
    <div
      style={{
        height: "200px",
        width: "200px",
        backgroundColor: "red",
        marginTop: "16px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "16px",
      }}
    >
      <div>some product box</div>
      <button
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation();
          alert("added to cart");
        }}
      >
        Add product to cart
      </button>
    </div>
  );
}
```

For now I use `data-disable-nprogress` on those Links.

**Comment by Skyleen77** [comment]
Upgrade to 2.3.10 and use data-prevent-nprogress={true} on the item to be disabled : 
```jsx
<button
   data-prevent-nprogress={true}
   onClick={(e) => {
      e.preventDefault();
      e.stopPropagation();
      alert("added to cart");
   }}
>
   Add product to cart
</button>
```

This should fix the problem.

**Comment by ciruz** [comment]
Thank you, it works great now.
