### ISSUE TITLE
Error: navigation.usePathname is not a function

### ISSUE THREAD

**Issue by begalinsaf** [Skyleen77/next-nprogress-bar#58]
can you help me with this error

```bash 
Error: navigation.usePathname is not a function
```

im in Nextjs 14.2.2 intalled with Bun

**Comment by hideyuki** [comment]
@begalinsaf 
Same issue
It may be necessary to use it only for the client component

Please try to put `'use client'` on top of the code that uses the <ProgressBar>

**Comment by begalinsaf** [comment]
I've done all the configuration for the app router, including 'use client' on the provider, but I don't know what's causing the issue. Maybe there's a conflict between my code and this package, but for now, I'm using [nextjs-toploader](https://github.com/TheSGJ/nextjs-toploader). I'll close this issue. Thank you, everyone.

**Comment by f-steel** [comment]
had the same issue as you and also now using the other package @begalinsaf
