### ISSUE TITLE
How to position HTML element inline?

### ISSUE THREAD

**Issue by stefan-girlich** [Skyleen77/next-nprogress-bar#62]
I want to position the load indicator at a specific position within my application header. Is there a way to achieve this?

It seems that the HTML element containing the load indicator is always positioned somewhere high up in the hierarchy (probably directly inside `<body>`) regardless of where `<Progressbar />` is placed. I saw that the option `style` can be used to define custom styles, but it doesn't allow for placement within the DOM.

**Comment by grazianodev** [comment]
I was trying to achieve the same as @stefan-girlich, and it looks like NProgress does allow this by providing a 'parent' option, so you can do something like this:

```
<ProgressBar
    color='var(--progress-bar-color)'
    height='2px'
    options={{
        parent: '#app',
    }}
/> 
```
