### ISSUE TITLE
NProgressBar not working in my NextJs 14.2.2

### ISSUE THREAD

**Issue by IAmYoungbossy** [Skyleen77/next-nprogress-bar#63]
I have tried to implement this in my project following the documentation but the progress bar doesn't show when navigating between routes.

Below is my ProgressProvider component 

```js
"use client";

import { AppProgressBar as ProgressBar } from "next-nprogress-bar";

const ProgressProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  return (
    <>
      {children}
      <ProgressBar
        height="4px"
        color="#00bfff"
        options={{ showSpinner: true }}
        shallowRouting
      />
    </>
  );
};

export default ProgressProvider;

```

It is being imported and used in my RootLayout as shown below, but it's not working. Is there something I'm not doing right?

```js
// Styles
import "./globals.css";

// Packages
import localFont from "next/font/local";

// Components
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

// Providers
import AppProviders from "./provider";
import ProgressProvider from "./ProgressProvider";

export const product_sans = localFont({
  display: "swap",
  variable: "--product-sans",
  fallback: ["system-ui", "arial"],
  preload: false,
  src: [
    {
      weight: "900",
      style: " normal",
      path: "./fonts/ProductSans-Black.ttf",
    },
    {
      weight: "900",
      style: " italic",
      path: "./fonts/ProductSans-BlackItalic.ttf",
    },
    {
      weight: "700",
      style: " normal",
      path: "./fonts/ProductSans-Bold.ttf",
    },
    {
      weight: "700",
      style: " italic",
      path: "./fonts/ProductSans-BoldItalic.ttf",
    },
    {
      weight: "400",
      style: " italic",
      path: "./fonts/ProductSans-Italic.ttf",
    },
    {
      weight: "300",
      style: " normal",
      path: "./fonts/ProductSans-Light.ttf",
    },
    {
      weight: "300",
      style: " italic",
      path: "./fonts/ProductSans-LightItalic.ttf",
    },
    {
      weight: "500",
      style: " normal",
      path: "./fonts/ProductSans-Medium.ttf",
    },
    {
      weight: "500",
      style: " italic",
      path: "./fonts/ProductSans-MediumItalic.ttf",
    },
    {
      weight: "400",
      style: " normal",
      path: "./fonts/ProductSans-Regular.ttf",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${product_sans.className} relative min-h-screen`}
      >
        <ProgressProvider>
          <AppProviders>
            <Header />
            <main>{children}</main>
            <Footer />
          </AppProviders>
        </ProgressProvider>
      </body>
    </html>
  );
}
```

Any help would be very much appreciated. Thanks

**Comment by IAmYoungbossy** [comment]
> I have tried to implement this in my project following the documentation but the progress bar doesn't show when navigating between routes.
> 
> Below is my ProgressProvider component
> 
> ```js
> "use client";
> 
> import { AppProgressBar as ProgressBar } from "next-nprogress-bar";
> 
> const ProgressProvider = ({
>   children,
> }: {
>   children: React.ReactNode;
> }) => {
>   return (
>     <>
>       {children}
>       <ProgressBar
>         height="4px"
>         color="#00bfff"
>         options={{ showSpinner: true }}
>         shallowRouting
>       />
>     </>
>   );
> };
> 
> export default ProgressProvider;
> ```
> 
> It is being imported and used in my RootLayout as shown below, but it's not working. Is there something I'm not doing right?
> 
> ```js
> // Styles
> import "./globals.css";
> 
> // Packages
> import localFont from "next/font/local";
> 
> // Components
> import { Footer } from "@/components/Footer";
> import { Header } from "@/components/Header";
> 
> // Providers
> import AppProviders from "./provider";
> import ProgressProvider from "./ProgressProvider";
> 
> export const product_sans = localFont({
>   display: "swap",
>   variable: "--product-sans",
>   fallback: ["system-ui", "arial"],
>   preload: false,
>   src: [
>     {
>       weight: "900",
>       style: " normal",
>       path: "./fonts/ProductSans-Black.ttf",
>     },
>     {
>       weight: "900",
>       style: " italic",
>       path: "./fonts/ProductSans-BlackItalic.ttf",
>     },
>     {
>       weight: "700",
>       style: " normal",
>       path: "./fonts/ProductSans-Bold.ttf",
>     },
>     {
>       weight: "700",
>       style: " italic",
>       path: "./fonts/ProductSans-BoldItalic.ttf",
>     },
>     {
>       weight: "400",
>       style: " italic",
>       path: "./fonts/ProductSans-Italic.ttf",
>     },
>     {
>       weight: "300",
>       style: " normal",
>       path: "./fonts/ProductSans-Light.ttf",
>     },
>     {
>       weight: "300",
>       style: " italic",
>       path: "./fonts/ProductSans-LightItalic.ttf",
>     },
>     {
>       weight: "500",
>       style: " normal",
>       path: "./fonts/ProductSans-Medium.ttf",
>     },
>     {
>       weight: "500",
>       style: " italic",
>       path: "./fonts/ProductSans-MediumItalic.ttf",
>     },
>     {
>       weight: "400",
>       style: " normal",
>       path: "./fonts/ProductSans-Regular.ttf",
>     },
>   ],
> });
> 
> export default function RootLayout({
>   children,
> }: Readonly<{
>   children: React.ReactNode;
> }>) {
>   return (
>     <html lang="en">
>       <body
>         className={`${product_sans.className} relative min-h-screen`}
>       >
>         <ProgressProvider>
>           <AppProviders>
>             <Header />
>             <main>{children}</main>
>             <Footer />
>           </AppProviders>
>         </ProgressProvider>
>       </body>
>     </html>
>   );
> }
> ```
> 
> Any help would be very much appreciated. Thanks

Hello everyone,

I was able to find the solution for why the progress bar was not displaying in my Next.js app. The implementation as posted above is fine and should work in your project.

### Key Issue: z-index Conflict

The issue was that the z-index of my header component was higher than the default z-index set on the NProgress element. To resolve this, I had to target the progress bar element with the following CSS rule:

#### css

```css
#nprogress .bar {
  z-index: 99999 !important;
}
```

### Updated ProgressBar Settings
I also updated some of the settings on the ProgressBar component as shown below:

#### jsx
```js
"use client";

import { AppProgressBar as ProgressBar } from "next-nprogress-bar";

const ProgressProvider = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      {children}
      <ProgressBar
        height="6px"
        shallowRouting
        color="#f69446"
        options={{ showSpinner: true }}
      />
    </>
  );
};

export default ProgressProvider;
```
### Additional Note

Another thing I noticed is that most times for your settings to be updated properly, you have to restart your server.

---

I have resolved the issue on my end. Please feel free to close the issue if you find this solution acceptable. Thank you!

**Comment by leeansilva** [comment]
Thank you so much

**Comment by pritithakur** [comment]
import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Events Booking App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <ProgressBar
        height="4px"
        color="#00bfff"
        options={{ showSpinner: true }}
        shallowRouting
      />
      </body>
    </html>
  );
}
``
I am using this but when I am starting my application why is it giving me error as Error: navigation.usePathname is not a function

**Comment by acatzk** [comment]
This is not working in next.js app directory version 14.2.4

**Comment by IAmYoungbossy** [comment]
> This is not working in next.js app directory version 14.2.4

Can you show your implementation process and any error you're getting?

**Comment by acatzk** [comment]
@IAmYoungbossy No error at all. I follow the instruction given above but nothing works.

**Comment by IAmYoungbossy** [comment]
> @IAmYoungbossy No error at all. I follow the instruction given above but nothing works.

Have you checked the `z-index` value of your header component to make sure it's not higher than the default `z-index` set on NProgressBar? That was the issue I faced too. @acatzk 

You can increase the `z-index` of your NprogressBar by using the selector below in your CSS file

```css
#nprogress .bar {
  z-index: 99999 !important;
}
```

**Comment by acatzk** [comment]
> > @IAmYoungbossy No error at all. I follow the instruction given above but nothing works.
> 
> Have you checked the `z-index` value of your header component to make sure it's not higher than the default `z-index` set on NProgressBar? That was the issue I faced too. @acatzk
> 
> You can increase the `z-index` of your NprogressBar by using the selector below in your CSS file
> 
> ```css
> #nprogress .bar {
>   z-index: 99999 !important;
> }
> ```
![Screenshot_1](https://github.com/Skyleen77/next-nprogress-bar/assets/38458781/a17aae6d-a209-40ab-8f54-a780c1b6babe)


Yep Nothing happens

**Comment by IAmYoungbossy** [comment]
> > > @IAmYoungbossy No error at all. I follow the instruction given above but nothing works.
> > 
> > 
> > Have you checked the `z-index` value of your header component to make sure it's not higher than the default `z-index` set on NProgressBar? That was the issue I faced too. @acatzk
> > You can increase the `z-index` of your NprogressBar by using the selector below in your CSS file
> > ```css
> > #nprogress .bar {
> >   z-index: 99999 !important;
> > }
> > ```
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/38458781/346556437-a17aae6d-a209-40ab-8f54-a780c1b6babe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDA5MDksIm5iZiI6MTcyMDQ0MDYwOSwicGF0aCI6Ii8zODQ1ODc4MS8zNDY1NTY0MzctYTE3YWFlNmQtYTIwOS00MGFiLThmNTQtYTc4MGMxYjZiYWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyMTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YWFlYTMyMGYxYmRlMmEyZTBjZmM1OWJjNzY4ODNlYzlkYWNlZGYyMzhjMjVlMDkzMjM5NmRmM2ZkNDNkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmCSI7d0sIP1DcJRUv2m011--OOn15CCXXl5_yGOa-U)
> 
> Yep Nothing happens

Open your dev tool console, click on the element tab and try to navigate to a different route. While navigating check if the `nprogress-busy` class is injected into your html tag as shown below. If it is then one of your element has a higher `z-index` than what is set on progressBar element.

If nothing is being injected then check if your ProgressBar provider is imported and used used in your root layout.

![image](https://github.com/Skyleen77/next-nprogress-bar/assets/99342564/bec1e05b-85db-4a33-a465-70e46ed5bb05)

**Comment by Skyleen77** [comment]
I increase the z-index to 99999 in the last version

**Comment by jonasfroeller** [comment]
> I increase the z-index to 99999 in the last version

you should do 2147483647, as that's the maximum
