### ISSUE TITLE
AppProgressBar.tsx should have a `use client` directive

### ISSUE THREAD

**Issue by gustaveWPM** [Skyleen77/next-nprogress-bar#64]
Here: https://github.com/Skyleen77/next-nprogress-bar/blob/main/src/AppProgressBar.tsx

The code should start with `"use client";`

**Comment by gustaveWPM** [comment]
Related to: https://github.com/Skyleen77/next-nprogress-bar/issues/58

**Comment by osdiab** [comment]
for what it's worth I just put `"use client";` in the component where I use this component, but given this is a NextJS library wouldn't hurt
