### ISSUE TITLE
NProgressBar not working in my NextJs 14.2.4

### ISSUE THREAD

**Issue by acatzk** [Skyleen77/next-nprogress-bar#69]

**Comment by JWPapi** [comment]
For me neither.

**Comment by acatzk** [comment]
@Skyleen77 I want you to test in next.js 14.2.4 app directory if will works on your end

**Comment by Skyleen77** [comment]
> @Skyleen77 I want you to test in next.js 14.2.4 app directory if will works on your end

@acatzk For me it works perfectly.
How did you set up your Progress Bar?

**Comment by acatzk** [comment]
> > @Skyleen77 I want you to test in next.js 14.2.4 app directory if will works on your end
> 
> @acatzk For me it works perfectly. How did you set up your Progress Bar?

- Install next.js 14.2.4
- Install shadcn-ui
- Install package `npm install next-nprogress-bar`


create file
`ProgressBarProvider.jsx`

```
'use client';

import { AppProgressBar as ProgressBar } from 'next-nprogress-bar';

const Providers = ({ children }) => {
  return (
    <>
      {children}
      <ProgressBar
        height="4px"
        color="#fffd00"
        options={{ showSpinner: false }}
        shallowRouting
      />
    </>
  );
};

export default Providers;
```


```
/app/layout.jsx
// Import and use it in /app/layout.jsx
import Providers from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
```


go to global.css
```
#nprogress .bar {
  z-index: 99999 !important;
}
```

**Comment by Skyleen77** [comment]
For my part this works, and z-index 9999 was added by default in the latest version.

You say create a file `ProgressBarProvider.jsx` and you import another file in the layout `import Providers from './providers';`. Is this normal?

**Comment by acatzk** [comment]
@Skyleen77 

## I install package

`npm i next-nprogress-bar`

in my styles folder I have two files
- globals.css
   ```
   @import url('./tailwind.css');
    #nprogress .bar {
      z-index: 99999 !important;
    }
  `
## tailwind.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;

    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;

    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;

    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;

    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;

    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;

    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;

    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;

    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;

    --radius: 0.5rem;

    --pg-primary: #836fff;
    --pg-secondary: #15f5ba;
    --pg-navy: #211951;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;

    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;

    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;

    --primary: 210 40% 98%;
    --primary-foreground: 222.2 47.4% 11.2%;

    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;

    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;

    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;

    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;

    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 212.7 26.8% 83.9%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-slate-900 text-slate-300 antialiased;
  }
}

@layer components {
  .custom-scrollbar {
    @apply scrollbar-thin scrollbar-track-transparent scrollbar-thumb-slate-700 scrollbar-thumb-rounded-md;
  }
  .custom-focus-outline {
    @apply transition-colors duration-200 ease-in-out focus:outline-none focus:outline-offset-2 focus:outline-pg-secondary;
  }
}
```

## this is my root next-progress-bar.tsx
``` 
 'use client'
  
  import React, { ReactNode } from 'react'
  import { AppProgressBar as ProgressBar } from 'next-nprogress-bar'
  
  type NextProgressBarProps = {
    children: ReactNode
  }
  
  export const NextProgressBar = ({ children }: NextProgressBarProps): JSX.Element => {
    return (
      <>
        <ProgressBar height="4px" color="#fffd00" options={{ showSpinner: false }} shallowRouting />
        {children}
      </>
    )
  }
```


### imported in the layout.tsx
```
  import { ReactNode } from 'react'
import type { Metadata } from 'next'

import '~/styles/globals.css'
import { cn } from '~/lib/utils'
import { root } from '~/constant/metadata'
import { fontSans } from '~/constant/font'
import { Toaster } from '~/components/ui/sonner'
import { ModalProvider } from '~/components/providers/modal-providers'
import { NextProgressBar } from '~/components/providers/next-progress-bar'

export const metadata: Metadata = root

type RootLayoutProps = Readonly<{
  children: ReactNode
}>

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="en">
      <body className={cn(fontSans.className)}>
        <Toaster position="bottom-left" />
        <ModalProvider />
        <NextProgressBar>{children}</NextProgressBar>
      </body>
    </html>
  )
}
```


ALL OF THIS CODE STILL NOT WORKING

this is my package.json
```
{
  "name": "pickupgo-superadmin",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "check-types": "tsc --pretty --noEmit",
    "check-format": "prettier --check .",
    "check-lint": "next lint",
    "format": "prettier --write .",
    "check-all": "npm run check-format && npm run check-lint && npm run check-types && npm run build"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.9.0",
    "@radix-ui/react-accordion": "^1.2.0",
    "@radix-ui/react-aspect-ratio": "^1.1.0",
    "@radix-ui/react-avatar": "^1.1.0",
    "@radix-ui/react-dialog": "^1.1.1",
    "@radix-ui/react-dropdown-menu": "^2.1.1",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-select": "^2.1.1",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.2",
    "@tanstack/match-sorter-utils": "^8.15.1",
    "@tanstack/react-table": "^8.19.3",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-react": "^0.400.0",
    "next": "14.2.4",
    "next-nprogress-bar": "^2.3.13",
    "next-themes": "^0.3.0",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.52.1",
    "sonner": "^1.5.0",
    "tailwind-merge": "^2.3.0",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.23.8",
    "zustand": "^4.5.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8.57.0",
    "eslint-config-next": "^14.2.4",
    "postcss": "^8",
    "prettier": "^3.3.2",
    "prettier-plugin-tailwindcss": "^0.6.5",
    "tailwind-scrollbar": "^3.1.0",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.4.3"
  }
}

```

**Comment by acatzk** [comment]
@Skyleen77 
I see the problem now, it is because I used the `router.push` instead of `Link` component
