### ISSUE TITLE
Add support for passing a custom router

### ISSUE THREAD

**Issue by ahmedriad1** [Skyleen77/next-nprogress-bar#73]
When using a localization library, in this case `next-intl`, you have to use their router so that they can handle locales when changing the url. 

Example:
```ts
import { createSharedPathnamesNavigation } from "next-intl/navigation";

const navigation = createSharedPathnamesNavigation({ locales: PATH_LOCALES });

// localized router
navigation.useRouter
```

This means there is currently no way to use `next-nprogress-bar`'s router.

## Ask
Provide a function that accepts a `useRouter` hook, and returns a modified version of it that supports nprogress as well.

Example:
```ts
import { makeNprogressRouter } from 'next-nprogress-bar';
import { createSharedPathnamesNavigation } from "next-intl/navigation";

const navigation = createSharedPathnamesNavigation({ locales: PATH_LOCALES });

export const useRouter = makeNprogressRouter(navigation.useRouter);
```

**Comment by Skyleen77** [comment]
By upgrading to version `2.3.15` you should be able to do :
```jsx
import { useRouter as useNextIntlRouter } from "next-intl";
const router = useRouter(useNextIntlRouter);

router.push('/about');
router.replace('/?counter=10');
router.back();
```

**Comment by ahmedriad1** [comment]
Perfect, thank you @Skyleen77 !

**Comment by emretfn** [comment]
@Skyleen77 Hi, it doesnt accept type-safe router. If u use pathnames (localized) on next-intl the createNavigation function returns type-safe useRouter and your useRouter just accepts AppRouterInstance type.
